#!/usr/bin/env bash
# redirect a new direction with 301

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=SK9KEwE6JmE permanent;"
sed -i "19i $str" /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx restart
