#!/usr/bin/env bash
# install an d configure HAProxy
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
apt-get install haproxy=2.0.\* -y
front="frontend 771-lb-01
        bind *:80
        mode http
        default_backend My_Web_Servers"
back="backend My_Web_Servers
        mode http
        balance roundrobin
        option forwardfor
        option httpchk HEAD / HTTP/1.1rnHost:localhost
        server 771-web-01 35.237.63.104:80 check
        server 771-web-02 104.196.166.224:80 check"
echo -e "$front\n$back" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
