#!/usr/bin/env bash
echo $$ > '/var/run/holbertonscript.pid' 
trap 'rm /var/run/holbertonscript.pid; echo I hate the kill command; kill -9 $$' 15
trap 'echo Y U no love me?!' 2
trap 'rm /var/run/holbertonscript.pid; exit' 3
while :
do
    echo To infinity and beyond
    sleep 2
done
