#!/usr/bin/env bash
#Print strin g in a loop while
x=1
while ((x <= 20))
do
    echo "$x"
    case "$x" in
        4) echo "bad luck from China" 
            ;;
        9) echo "bad luck from Japan" 
            ;;
        17) echo "bad luck from Italy" 
            ;;
    esac
    ((x++))
done
