#!/usr/bin/env bash
# fix the file nginx.conf changit the permitions
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's!listen 80 default_server!listen 8080 default_server!' /etc/nginx/sites-available/default
sed -i 's!80 !8080 !' /etc/nginx/sites-available/default
su - nginx -c 'service nginx start'
